with source as (
    select * from {{ source('supplycopia_raw', var('consumption_source_file')) }}
),

uom_mapping as (
    select * from {{ ref('uom_mappings') }}
),

parsed as (
    select
        {{ clean_string('LOG_ID') }} as log_id,
        {{ clean_string('FACILITY') }} as facility,
        {{ clean_string('MEDICAL_RECORD_NUMBER') }} as medical_record_number,
        {{ clean_string('"CASE_ID / ENCOUNTER FHIR ID"') }} as case_id,
        {{ clean_string('"CASE_ID / ENCOUNTER FHIR ID"') }} as "CASE_ID / ENCOUNTER FHIR ID",
        {{ clean_string('DRG_CODE') }} as drg_code,
        {{ clean_string('SURGICAL_HIERARCHY') }} as surgical_hierarchy,
        {{ clean_string('SURGICAL_HIERARCHY') }} as "SURGICAL_HIERARCHY",
        {{ clean_string('BILLED_CPT_CODE') }} as billed_cpt_code,
        {{ clean_string('BILLED_CPT_CODE') }} as "BILLED_CPT_CODE",
        {{ clean_string('PRIMARY_ICD10_PX_CODE') }} as primary_icd10_px_code,
        {{ clean_string('PRIMARY_ICD10_PX_CODE') }} as "PRIMARY_ICD10_PX_CODE",
        {{ clean_string('PRIMARY_PROCEDURE') }} as primary_procedure,
        {{ clean_string('SERVICE_LINE') }} as service_line,
        {{ clean_string('PATIENT_TYPE') }} as patient_type,
        {{ clean_string('LEAD_SURGEON') }} as lead_surgeon,
        {{ clean_string('PAYOR_GROUP') }} as payor_group,
        {{ clean_string('PAYOR_GROUP') }} as "PAYOR_GROUP",
        {{ safe_cast('ADMIT_DATE_TIME', 'timestamp') }} as admit_date_time,
        {{ safe_cast('DISCHARGE_DATE_TIME', 'timestamp') }} as discharge_date_time,
        {{ safe_cast('LOS', 'double') }} as length_of_stay,
        {{ safe_cast('LOS', 'double') }} as "LOS",
        {{ safe_cast('GMLOS', 'double') }} as gmlos,
        {{ safe_cast('GMLOS', 'double') }} as "GMLOS",
        {{ clean_string('ACCOUNT_NUMBER') }} as account_number,
        {{ safe_cast('CONTRACT_PRICE', 'double') }} as contract_price,
        {{ safe_cast('TOTAL_ACQUISITION_COST', 'double') }} as total_acquisition_cost,
        {{ safe_cast('SUPPLY_UNIT_PRICE', 'double') }} as supply_unit_price,
        {{ safe_cast('TOTAL_QUANTITY', 'double') }} as total_quantity,
        {{ safe_cast('IMPLANT_VAR_DIRECT_COST', 'double') }} as implant_var_direct_cost,
        {{ safe_cast('IMPLANT_VAR_DIRECT_COST', 'double') }} as "IMPLANT_VAR_DIRECT_COST",
        {{ safe_cast('MED_SUPPLY_VAR_DIRECT_COST', 'double') }} as med_supply_var_direct_cost,
        {{ safe_cast('MED_SUPPLY_VAR_DIRECT_COST', 'double') }} as "MED_SUPPLY_VAR_DIRECT_COST",
        {{ safe_cast('TOTAL_CHARGES', 'double') }} as total_charges,
        {{ safe_cast('TOTAL_ACCT_BAL', 'double') }} as total_acct_bal,
        {{ safe_cast('TOTAL_ACCT_BAL', 'double') }} as "TOTAL_ACCT_BAL",
        {{ safe_cast('TOTAL_ADJ', 'double') }} as total_adj,
        {{ safe_cast('TOTAL_ADJ', 'double') }} as "TOTAL_ADJ",
        {{ safe_cast('TOTAL_PMTS', 'double') }} as total_pmts,
        {{ safe_cast('TOTAL_PMTS', 'double') }} as "TOTAL_PMTS",
        {{ clean_string('"SSI (0/1)"') }} as ssi_flag,
        {{ clean_string('"SSI (0/1)"') }} as "SSI (0/1)",
        {{ clean_string('"BLOOD_TRANSFUSION_FLAG (0/1)"') }} as blood_transfusion_flag,
        {{ clean_string('"BLOOD_TRANSFUSION_FLAG (0/1)"') }} as "BLOOD_TRANSFUSION_FLAG (0/1)",
        {{ clean_string('"READMISSION_INDEX_CASE (0/1)"') }} as readmission_index_case,
        {{ clean_string('"READMISSION_INDEX_CASE (0/1)"') }} as "READMISSION_INDEX_CASE (0/1)",
        {{ clean_string('"MORTALITY (0/1)"') }} as mortality_flag,
        {{ clean_string('"MORTALITY (0/1)"') }} as "MORTALITY (0/1)",
        {{ clean_string('"RISK OF MORTALITY"') }} as risk_of_mortality,
        {{ clean_string('"RISK OF MORTALITY"') }} as "RISK OF MORTALITY",
        {{ clean_string('MANUFACTURER_NAME') }} as manufacturer_name,
        {{ clean_string('MANUFACTURER_CATALOG_NUMBER') }} as manufacturer_catalog_number,
        {{ clean_string('ITEM_NUMBER') }} as item_number,
        {{ clean_string('ITEM_DESCRIPTION') }} as item_description,
        {{ clean_upper('ITEM_UOM') }} as raw_item_uom,
        {{ safe_cast('ITEM_QOE', 'double') }} as item_qoe,
        {{ safe_cast('ITEM_QOE', 'double') }} as "ITEM_QOE",
        {{ clean_upper('SUPPLIER') }} as supplier,
        {{ clean_string('CONTRACT_CATEGORY') }} as contract_category,
        {{ clean_string('SPEND_CATEGORY') }} as spend_category,
        {{ clean_upper('UNSPSC_CODE') }} as unspsc_code,
        {{ clean_string('CONTRACT_FLAG') }} as contract_flag,
        {{ clean_string('ASA_RATING') }} as asa_rating,
        {{ clean_string('ASA_RATING') }} as "ASA_RATING",
        {{ clean_string('BMI_BUCKET') }} as bmi_bucket,
        {{ clean_string('BMI_BUCKET') }} as "BMI_BUCKET",
        {{ clean_string('"ROBOTICS (0/1)"') }} as robotics_flag,
        {{ clean_string('"ROBOTICS (0/1)"') }} as "ROBOTICS (0/1)",
        {{ clean_string('SMOKING_STATUS') }} as smoking_status,
        {{ clean_string('SMOKING_STATUS') }} as "SMOKING_STATUS",
        {{ clean_string('"DIABETIC_STATUS (0/1)"') }} as diabetic_status,
        {{ clean_string('"DIABETIC_STATUS (0/1)"') }} as "DIABETIC_STATUS (0/1)",
        {{ clean_string('PATIENT_AGE_BUCKET') }} as patient_age_bucket,
        {{ clean_string('PATIENT_AGE_BUCKET') }} as "PATIENT_AGE_BUCKET",
        {{ clean_string('PATIENT_GENDER') }} as patient_gender,
        {{ clean_string('PATIENT_GENDER') }} as "PATIENT_GENDER",
        {{ clean_string('ETHNICITY') }} as ethnicity,
        {{ clean_string('ETHNICITY') }} as "ETHNICITY"
    from source
),

standardized as (
    select
        p.*,
        coalesce(u.standard_uom, case when p.raw_item_uom in ('EACH', 'EACHES') then 'EA' when p.raw_item_uom in ('CASE', 'CS') then 'CA' when p.raw_item_uom in ('BOX', 'BX') then 'BX' else coalesce(p.raw_item_uom, 'EA') end) as item_uom,
        coalesce(u.ea_conversion_factor, 1.0) as uom_conversion_factor,
        {{ append_metadata('consumption_source_file', ['p.log_id', 'p.item_number', 'p.admit_date_time', 'p.supply_unit_price']) }}
    from parsed p
    left join uom_mapping u on p.raw_item_uom = u.uom_code
)

select * from standardized
